ALTER TABLE "Monitor" ADD COLUMN "method" TEXT NOT NULL DEFAULT 'GET';
ALTER TABLE "Monitor" ADD COLUMN "expectedStatusCode" INTEGER NOT NULL DEFAULT 200;
ALTER TABLE "Monitor" ADD COLUMN "timeoutSeconds" INTEGER NOT NULL DEFAULT 5;
