ALTER TABLE "Monitor" ADD COLUMN "isPublic" BOOLEAN NOT NULL DEFAULT true;
ALTER TABLE "Monitor" ADD COLUMN "publicName" TEXT;
ALTER TABLE "Monitor" ADD COLUMN "showUrl" BOOLEAN NOT NULL DEFAULT false;
